configfile: config.json
keep-going: true
rerun-incomplete: true
quiet: rules

cores: all

# number of threads used by each rule
set-threads:
  - tier_ver=1
  - tier_raw=1

# memory and runtime requirements for each single rule
# - https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources
# - https://docs.nersc.gov/jobs/#available-memory-for-applications-on-compute-nodes
set-resources:
  - tier_ver:mem_mb=1000
  - tier_ver:runtime=120
  - tier_raw:mem_mb=1000
  - tier_raw:runtime=120
