configfile: config.json
cores: 200

# NOTE: should actually set this through the command line, since there is a
# scratch directory for each the user
#   $ snakemake --shadow-prefix "$PSCRATCH" [...]
shadow-prefix: "/pscratch/sd/p/pertoldi"

cluster: slurm
local-cores: 50
default_resources:
  - slurm_account: m2676
  - constraint: cpu
  - runtime: 6:00:00
  - slurm_extra: "--qos=long --mail-type=begin,end,fail --mail-user=luigi.pertoldi@tum.de --licenses=scratch,cfs"
