configfile: config.json
keep-going: true
rerun-incomplete: true
quiet: rules

# profit from Perlmutter's scratch area: https://docs.nersc.gov/filesystems/perlmutter-scratch
# NOTE: should actually set this through the command line, since there is a
# scratch directory for each user:
#   $ snakemake --shadow-prefix "$PSCRATCH" [...]
# shadow-prefix: "$PSCRATCH"

# maximum number of cores requested from the cluster or cloud scheduler
cores: 128

# number of threads used by each rule
set-threads:
  - build_tier_ver=1
  - build_tier_raw=1

# memory and runtime requirements for each single rule
# - https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources
# - https://docs.nersc.gov/jobs/#available-memory-for-applications-on-compute-nodes
set-resources:
  - build_tier_ver:mem_mb=1000
  - build_tier_ver:runtime=120
  - build_tier_raw:mem_mb=1000
  - build_tier_raw:runtime=120
